var obj = {
    song: "王宇宙Leto,乔浚丞", value: "若月亮没来 (若是月亮还没来)",
    song: "吉星出租", value: "暮色回响",
    song: "郭有才", value: "诺言 (郭有才版)",
    song: "海来阿木", value: "西楼儿女",
    song: "王睿卓", value: "重生之我在异乡为异客",
    song: "岳云鹏", value: "西楼儿女",
    song: "周林枫", value: "阿嬷 (爱国版)",
    song: "周深", value: "小美满",
    song: "就是南方凯", value: "列车开往春天+(DJHZ版)",
    song: "徐佳莹", value: "身骑白马",
    song: "张妙格", value: "我期待的不是雪",
    song: "韦礼安", value: "如果可以",
    song: "江语晨", value: "最后一页",
    song: "蔡依林", value: "妥协",
    song: "于冬然", value: "其实都没有",
    song: "郑润泽", value: "瞬",
    song: "就是南方凯", value: "离别开出花（弹唱版）",
    song: "就是南方凯", value: "离别开出花",
    song: "徐薇", value: "面具",
    song: "毛不易", value: "无名的人",
    song: "郑浩", value: "须尽欢",
    song: "凤凰传奇", value: "奢香夫人",
    song: "刀郎", value: "罗刹海市",
    song: "珂拉琪", value: "万千花蕊慈母悲哀",
    song: "柯柯柯啊", value: "姑娘别哭泣",
    song: "浩然H_R", value: "年少的你啊",
    song: "小霞,海洋Bo", value: "向云端",
    song: "郭顶", value: "凄美地",
    song: "葛东琪", value: "悬溺",
    song: "承桓", value: "我会等",
    song: "程响", value: "可能",
    song: "张碧晨", value: "笼",
    song: "蔡健雅", value: "Letting Go",
    song: "苏星婕", value: "听悲伤的情歌",
    song: "闻人听書_", value: "一笑江湖",
    song: "赵雷", value: "我记得",
    song: "周星星", value: "毒药",
    song: "刀郎", value: "花妖",
    song: "贺仙人", value: "你的",
    song: "袁小葳,KyL3", value: "别无所爱",
    song: "小咪", value: "我走后",
    song: "王蓝茵", value: "恶作剧",
    song: "张紫豪", value: "可不可以",
    song: "周传雄", value: "黄昏",
    song: "郑润泽", value: "如果呢",
    song: "柯柯柯啊", value: "姑娘在远方",
    song: "容祖儿", value: "就让这大雨全都落下",
    song: "那艺娜", value: "爱如火",
    song: "王菲", value: "如愿",
    song: "任夏", value: "悲伤的爱情",
    song: "卦者灵风", value: "阳光开朗大男孩",
    song: "A-Lin", value: "天若有情",
    song: "指尖笑", value: "不问ciaga (不问别离)",
    song: "李荣浩", value: "乌梅子酱",
    song: "一只白羊", value: "等不到的你",
    song: "宝石Gem", value: "电梯战神",
    song: "群星", value: "勇气大爆发",
    song: "袁树雄", value: "早安隆回",
    song: "张碧晨", value: "开往早晨的午夜",
    song: "3秒超市", value: "一半疯了一半算了",
    song: "一只白羊", value: "赐我",
    song: "梦然", value: "是你",
    song: "小洲", value: "爱都爱了",
    song: "王子健", value: "循迹",
    song: "周林枫", value: "忘了",
    song: "Zyboy忠宇", value: "妈妈的话",
    song: "程今", value: "爱是无畏的冒险",
    song: "叶斯淳", value: "我曾遇到一束光",
    song: "星野", value: "晚风告白",
    song: "郁可唯", value: "去有风的地方",
    song: "周杰伦", value: "晴天",
    song: "Capper,罗言", value: "雪 Distance",
    song: "蓝心羽", value: "寂寞烟火",
    song: "云汐", value: "故事还长",
    song: "30年前，50年后", value: "精卫",
    song: "龍猛寺寬度", value: "武家坡2021",
    song: "盛哲", value: "在你的身边",
    song: "戚薇", value: "如果爱忘了",
    song: "王优秀", value: "墨尔本的秋天 (女版)",
    song: "Kirsty刘瑾睿", value: "若把你",
    song: "G_E_M_ 邓紫棋", value: "多远都要在一起",
    song: "张芸京", value: "偏爱",
    song: "原来是萝卜丫", value: "后来我们的爱 (萝卜版)",
    song: "1K", value: "就忘了吧",
    song: "五月天", value: "玫瑰少年",
    song: "阿梨粤", value: "晚风心里吹",
    song: "祥嘞嘞", value: "难却 (吉他版)",
    song: "南瓜", value: "与你到永久",
    song: "陈奕迅", value: "孤勇者",
    song: "告五人", value: "给你一瓶魔法药水",
    song: "七喜", value: "香水有毒 (七喜版)",
    song: "袁小葳 _ 阿辰（阎辰）", value: "化作烟火为你坠落",
    song: "古巨基", value: "必杀技",
    song: "詹雯婷", value: "诀爱",
    song: "杨培安", value: "爱上你是一个错",
    song: "树泽", value: "后来的你在哪",
    song: "周延英（英子-effie）", value: "回不去的从前",
    song: "LBI利比", value: "小城夏天",
    song: "张家旺", value: "迟来的情话",
    song: "ycccc", value: "满天星辰不及你",
    song: "玥夏", value: "木偶戏",
    song: "锤娜丽莎", value: "我太笨",
    song: "张韶涵 _ 王赫野", value: "篇章",
    song: "彭席彦,Franky弗兰奇", value: "再见莫妮卡",
    song: "队长", value: "哪里都是你",
    song: "旺仔小乔", value: "樱花树下的约定（完整版）",
    song: "温奕心", value: "一路生花",
    song: "告五人", value: "唯一",
    song: "周杰伦", value: "本草纲目",
    song: "pro", value: "等不来花开",
    song: "王心凌", value: "第一次爱的人",
    song: "队长", value: "黄礼格",
    song: "五月天", value: "后来的我们",
    song: "王心凌", value: "爱你",
    song: "柳爽", value: "漠河舞厅",
    song: "刘大拿,褚晨茜", value: "再见莫妮卡",
    song: "三叔说", value: "海市蜃楼",
    song: "豆包", value: "太想念",
    song: "黄龄 _ Tăng Duy Tân", value: "叹",
    song: "Zyboy忠宇", value: "堕",
    song: "小阿七", value: "从前说",
    song: "梅朵", value: "总以为来日方长",
    song: "林俊杰", value: "新地球",
    song: "于冬然", value: "从前怕",
    song: "告五人", value: "带我去找夜生活",
    song: "就是南方凯", value: "问心",
    song: "BY2", value: "爱丫爱丫",
    song: "王不醒", value: "月老掉线",
    song: "真瑞", value: "最美的瞬间",
    song: "Tank", value: "三国恋",
    song: "粉太狼", value: "命运",
    song: "雷佳", value: "人世间",
    song: "王天戈 _ 川青", value: "追寻你",
    song: "MELISA _ Tommo", value: "I'm Alone",
    song: "h3R3", value: "忘不掉的你",
    song: "莫文蔚", value: "这世界那么多人",
    song: "毛不易", value: "如你所想",
    song: "小蓝背心", value: "我怕来者不是你",
    song: "时代少年团", value: "渐暖",
    song: "海来阿木", value: "三生三幸",
    song: "徐佳莹", value: "一样的月光",
    song: "张齐山DanieL", value: "单人券",
    song: "Starling8,MoreLearn27,FIVESTAR", value: "苦茶子",
    song: "周深 _ GAI周延", value: "玫瑰少年 (Live)",
    song: "于冬然", value: "我的眼泪你的战利品",
    song: "薛之谦", value: "男二号",
    song: "品冠", value: "门没锁",
    song: "刘艺雯", value: "听闻远方有你",
    song: "李尖尖", value: "氧化氢",
    song: "刘至佳", value: "鲸语",
    song: "周杰伦", value: "花海",
    song: "Achim Reichel", value: "Aloha Heja He",
    song: "烟(许佳豪)", value: "删了吧",
    song: "Walk off the Earth,D Smoke", value: "Bet On Me",
    song: "yihuik苡慧", value: "麦浪",
    song: "薛之谦", value: "凤毛麟角",
    song: "等什么君(邓寓君) , FOX胡天渝", value: "踏雪",
    song: "梨冻紧,Wiz_H张子豪", value: "罗生门（Follow）",
    song: "队长", value: "予你",
    song: "Tăng Duy Tân _ BAE", value: "Dạ Vũ（夜舞）",
    song: "川青 _ Morerare", value: "下潜",
    song: "阿梨粤,DJR7", value: "秒针 (Dj版)",
    song: "程jiajia", value: "好想抱住你",
    song: "杜宣达", value: "指纹",
    song: "方大同", value: "特别的人",
    song: "苏星婕", value: "风吹过八千里",
    song: "洛先生", value: "影子说",
    song: "洛先生", value: "孤城",
    song: "邓典", value: "神魂颠倒",
    song: "伏仪", value: "时光采样 (钢琴版)",
    song: "付雪", value: "金玉良缘",
    song: "新地,卢克", value: "我不是刘德华",
    song: "邓岳章", value: "情意结",
    song: "海来阿木", value: "五十年以后",
    song: "苏星婕", value: "下雨夜",
    song: "莫叫姐姐", value: "当我娶过她",
    song: "苏星婕", value: "失眠播报",
    song: "金志文", value: "自娱自乐",
    song: "yihuik苡慧", value: "致你",
    song: "尹昔眠", value: "落在生命里的光",
    song: "郁可唯", value: "路过人间",
    song: "王搏", value: "穷叉叉",
    song: "阿吉太组合", value: "阿衣莫",
    song: "来一碗老于", value: "解药 (新版)",
    song: "程jiajia", value: "山楂树之恋",
    song: "满舒克", value: "以爱为囚",
    song: "王以太 _ 刘至佳", value: "危险派对",
    song: "yihuik苡慧", value: "银河与星斗",
    song: "烟(许佳豪)", value: "偏爱和例外",
    song: "王靖雯不胖", value: "说说话 (Live)",
    song: "周星星", value: "我看过",
    song: "王优秀", value: "想某人",
    song: "吕口口", value: "失忆 (正式版)",
    song: "陆三三", value: "后来的风",
    song: "The Kid LAROI,Justin Bieber", value: "Stay (Explicit)",
    song: "井胧,井迪儿", value: "骁",
    song: "INK,王忻辰,苏星婕", value: "落日与晚风",
    song: "Adele", value: "Easy On Me",
    song: "赵乃吉", value: "错都错了",
    song: "程响", value: "时光洪流",
    song: "回春丹", value: "初恋",
    song: "秦海清", value: "不如",
    song: "王靖雯不胖", value: "会吗",
    song: "小蓝背心", value: "目及皆是你",
    song: "刘耀文", value: "Got You",
    song: "A1 TRIP,Nick_Y", value: "Butterfly",
    song: "渡", value: "须尽欢",
    song: "王忻辰 _ 葛里", value: "等风吹散人海",
    song: "周杰伦", value: "夜曲",
    song: "蔡琴", value: "读你",
    song: "杜宣达", value: "原来我从未忘记你",
    song: "告五人", value: "唯一",
    song: "王小帅", value: "怨苍天变了心 (吉他版)",
    song: "程jiajia", value: "外婆说",
    song: "刘至佳,韩瞳", value: "时光背面的我",
    song: "LKer林柯", value: "满目星辰皆是你",
    song: "大籽,Lil E", value: "放空",
    song: "蔡琴", value: "读你",
    song: "颜人中", value: "有些",
    song: "赵乃吉", value: "曾经你说",
    song: "不是花火呀", value: "雨爱",
    song: "陈柯霓 (CHENge)", value: "死性不改",
    song: "任嘉伦", value: "如一",
    song: "未来星B3Rich", value: "无法坠入爱河",
    song: "李玉刚", value: "万疆",
    song: "周深", value: "若思念便思念",
    song: "Aioz", value: "22秒",
    song: "任然", value: "雀跃",
    song: "DP龙猪,Swei水,Rays陈袁", value: "风吹一夏",
    song: "赵芷彤Cassie", value: "桃桃心动",
    song: "宋孟君", value: "失眠的夜 (DJ热搜版)",
    song: "薛廷佑", value: "hallo每一天",
    song: "李小璐", value: "鲸落",
    song: "周杰伦", value: "反方向的钟",
    song: "阿肆", value: "热爱105°C的你",
    song: "是七叔呢", value: "半生雪",
    song: "郭正正,Old crab", value: "你的眼睛像星星",
    song: "房东的猫,陈婧霏", value: "New Boy",
    song: "Interupt,Luna LePage", value: "Power (In Your Soul)",
    song: "盖君炎", value: "我想要",
    song: "锦零", value: "恋爱画板",
    song: "周杰伦", value: "明明就",
    song: "Shawn Mendes", value: "Stitches",
    song: "任子墨", value: "那一刻心动",
    song: "S,H,E", value: "Ring Ring Ring",
    song: "姚六一", value: "雾里",
    song: "摩登兄弟刘宇宁", value: "烟火星辰",
    song: "郑鱼", value: "怎叹",
    song: "蓝心羽", value: "星辰不坠落",
    song: "张叶蕾", value: "还是劈开",
    song: "G_E_M_ 邓紫棋,王者荣耀", value: "无双的王者",
    song: "陈子晴", value: "陪你看星星",
    song: "薛之谦", value: "变废为宝",
    song: "莫叫姐姐", value: "你能不能不要离开我",
    song: "Daniel Powter", value: "Free Loop",
    song: "李巍", value: "守护着我的光",
    song: "彭小胖", value: "语病",
    song: "康姆士COM'Z", value: "你永远是我的宝贝，宝贝",
    song: "夏日入侵企画", value: "想去海边",
    song: "时代少年团", value: "傻瓜",
    song: "杨小壮", value: "最后的人",
    song: "颜人中", value: "有些",
    song: "Will Armex,Katy M", value: "You and I",
    song: "Uu", value: "小城小爱",
    song: "space x", value: "0321",
    song: "宋宇宁", value: "那年·年少",
    song: "阿YueYue", value: "不负人间",
    song: "龚俊", value: "Sweet",
    song: "阿冗", value: "未发送",
    song: "虎二", value: "窗",
    song: "莫叫姐姐", value: "不该用情 (女声版)",
    song: "莫叫姐姐", value: "风中有朵雨做的云 (粤语莫叫语版)",
    song: "蓝心羽", value: "漫步宇宙",
    song: "苏星婕", value: "等一场大雨",
    song: "刘大壮", value: "吉他初恋",
    song: "安苏羽,傅梦彤", value: "潮汐(Natural)",
    song: "Lil Ghost小鬼", value: "不良少年",
    song: "李荣浩", value: "不遗憾",
    song: "时代少年团", value: "小小孩",
    song: "刘大壮", value: "假装 (吉他版)",
    song: "24KGoldn,iann dior,Lil Ghost小鬼", value: "Mood (Lil Ghost Remix,Explicit)",
    song: "陈雅森", value: "下辈子不一定还能遇见你",
    song: "你的上好佳", value: "白鸽",
    song: "王源", value: "流星也为你落下来了",
    song: "任然", value: "一去不回的时光",
    song: "aespa (에스파)", value: "Next Level",
    song: "董嘉鸿", value: "几里之外",
    song: "郭镐鸣", value: "野摩托",
    song: "海来阿木", value: "烟雨人间",
    song: "橘子妹", value: "特别邀请",
    song: "金池", value: "谁不是",
    song: "Lil Ghost小鬼", value: "别叫我达芬奇 (Punk Version)",
    song: "Mai,法老,肯迪仔", value: "花,太阳,彩虹,你",
    song: "R1SE", value: "Find Me",
    song: "Quang Hùng MasterD", value: "Dễ Đến Dễ Đi",
    song: "Tizzy T,VaVa毛衍七,Jony J,布瑞吉Bridge,黄旭", value: "少数派报告",
    song: "莫叫姐姐", value: "下辈子不一定还能遇见你 (吉他版)",
    song: "穆哲熙", value: "自愈",
    song: "颜人中", value: "不舍",
    song: "Eric周兴哲", value: "离开你以后",
    song: "王忻辰,苏星婕", value: "去年花开",
    song: "白小白", value: "往后余生只爱你",
    song: "王力宏", value: "我们的歌",
    song: "RADWIMPS,十明", value: "すずめ",
    song: "海洋Bo,高睿", value: "我的美丽",
    song: "周杰伦", value: "兰亭序",
}


const fs = require('fs');
const path = require('path');

fs.readFile('./data.json', 'utf8', (err, data) => {
    if (err) {
      console.error('Error reading file:', err);
      return;
    }
    const jsonData = JSON.parse(data);
    jsonData.forEach(item => {
        copyeFile(item.path)
    });
    // console.log(jsonData);
  });

  function copyeFile(pathsrc) {
    const destinationFilePath = path.join('./myMusic', path.basename(pathsrc));
    fs.copyFile(pathsrc, destinationFilePath, (err) => {
        if (err) {
            console.error('复制文件时出现错误：', err);
        } else {
            console.log('文件复制成功！');
        }
    });    
  }

